# @package _global_

# specify here default training configuration
defaults:
  - _self_
  - datamodule: weather.yaml
  - model: rcnn.yaml
  - callbacks: default.yaml
  - logger: comet.yaml # set logger here or use command line (e.g. `python train.py logger=tensorboard`)
  - trainer: default.yaml
  - log_dir: default.yaml

  # experiment configs allow for version control of specific configurations
  # e.g. best hyperparameters for each combination of model and datamodule
  - experiment: null

  # debugging config (enable through command line, e.g. `python train.py debug=default)
  - debug: null

  # config for hyperparameter optimization
  - hparams_search: null # optuna.yaml

  # optional local config for machine/user specific settings
  # it's optional since it doesn't need to exist and is excluded from version control
  - optional local: default.yaml

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

# path to original working directory
# hydra hijacks working directory by changing it to the new log directory
# https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
original_work_dir: ${hydra:runtime.cwd}

# path to folder with data
data_dir: ${original_work_dir}/data/
dataset_name: "pdsi_voronezh.csv" # "precip_belgorod_20y_40x91.csv"
batch_size: 4
num_epochs: 120

# pretty print config at the start of the run using Rich library
print_config: True

# disable python warnings if they annoy you
ignore_warnings: True

# set False to skip model training
train: True

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
test: True

# seed for random number generators in pytorch, numpy and python.random
seed: null

# parameters of the model that are shared with dataloader
n_cells_hor: 40
n_cells_ver: 80
history_length: 6
periods_forward: 3

# default name for the experiment, determines logging folder path
# (you can overwrite this name in experiment configs)
name: ${dataset_name}_${model._target_}_forward_${periods_forward}
