_target_: src.datamodules.weather_datamodule.WeatherDataModule

data_dir: ${data_dir}  # data_dir is specified in config.yaml
dataset_name: ${dataset_name}  # dataset_name is specified in config.yaml
left_border: 0
down_border: 0
right_border: 200
up_border: 250
n_cells_hor: 100
n_cells_ver: 100
time_col: "date"
event_col: "val"
x_col: "x"
y_col: "y"
train_val_test_split: [0.8, 0.1, 0.1]
periods_forward: 12
history_length: 3
batch_size: ${batch_size}
num_workers: 0
pin_memory: False
