_target_: src.datamodules.weather_datamodule.WeatherDataModule

data_dir: ${data_dir}  # data_dir is specified in config.yaml
dataset_name: ${dataset_name}  # dataset_name is specified in config.yaml
left_border: 0
down_border: 0
right_border: 200
up_border: 250
n_cells_hor: ${n_cells_hor}
n_cells_ver: ${n_cells_ver}
time_col: "date"
event_col: "val"
x_col: "x"
y_col: "y"
train_val_test_split: [0.6, 0.2, 0.2]
periods_forward: ${periods_forward}
history_length: ${history_length}
data_start: 0
data_len: 500
batch_size: ${batch_size}
num_workers: 0
pin_memory: False
